name: Release and deploy Go-Fortune

on:
  push:
    branches:
    - 'v[0-9]+.[0-9]+'

jobs: 
  release-and-deploy:
    # OS that this workflow will be running on, must have space between key runs-on and value ubuntu
    runs-on: ubuntu-latest

    # list of steps to perform task
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node 16
      uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Install Railway
      run: npm i -g @railway/cli

    - name: Deploy
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}



