name: Release and deploy Go-Fortune

on:
  push:
    branches:
    - 'v[0-9]+.[0-9]+'

jobs: 
  release-and-deploy:
    # OS that this workflow will be running on, must have space between key runs-on and value ubuntu
    runs-on: ubuntu-latest

    # list of steps to perform task
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use Node 16
      uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Install Railway
      run: npm i -g @railway/cli

    - name: Deploy
      run: railway up
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

    - name: Send custom notification message
      id: slack
      uses: slackapi/slack-github-action@v1.23.0
      with:
        payload: |
          {
            "text": "slack notification",
            "blocks": [
              {
                "type": "header",
                "text": {
                  "type": "plain_text",
                  "text": "DipSA55 CI/CD Assignment Submission "
                }
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Name:*\nYeo Yuan Qi Amanda"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Matriculation:*\nA026589R"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Email:*\n<mailto:e1045764@u.nus.edu|e1045764@u.nus.edu>"
                  },
                  {
                    "type": "mrkdwn",
                    "text": "*Repository:*\n<https://github.com/yxmanz/CICDWorkshop.git|git://github.com/yxmanz/CICDWorkshop.git>"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "*Deployment:*\n<https://cicdworkshop-production.up.railway.app/|https://cicdworkshop-production.up.railway.app>"
                  }
                ]
              },
              {
                "type": "section",
                "fields": [
                  {
                    "type": "mrkdwn",
                    "text": "\n<https://cicdworkshop-production.up.railway.app/|Open Application>"
                  }
                ]
              }
            ]
          }
        `
      env:
        SLACKTEST_WEBHOOK_URL: ${{ secrets.SLACKTEST_WEBHOOK_URL }}
        SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK



